<a href="https://colab.research.google.com/github/enikeevaRAMZ/Innopolis_PISH/blob/main/%D0%94%D0%97_18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
df=pd.read_csv("US-News-Rankings-Liberal-Arts-Colleges-Through-2023.csv")

In [6]:
df

,College Name,State,IPEDS ID,2023,2022,2021,2020,2019,2018,2017,...,1995,1994,1993,1992,1991,1990,1989,1988,1986,1984
0,Williams College,MA,168342,1,1,1,1,1,1,1,...,2,2,1,1,3,3.0,3.0,1.0,1.0,2.0
1,Amherst College,MA,164465,2,2,2,2,2,2,2,...,1,1,2,3,1,2.0,2.0,4.0,3.0,1.0
2,Pomona College,CA,121345,3,4,4,5,5,6,7,...,5,5,5,5,6,4.0,5.0,6.0,7.0,9.0
3,Swarthmore College,PA,216287,4,3,3,3,3,3,4,...,3,3,3,2,2,1.0,1.0,2.0,2.0,2.0
4,Wellesley College,MA,168218,5,5,4,3,3,3,3,...,4,4,4,6,5,5.0,4.0,8.0,8.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,William Peace University,NC,199272,NaN,NaN,NaN,NaN,T2 (173-229),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
357,Williams Baptist University,AR,107877,NaN,T2 (168-222),T2 (171-221),T2 (164-215),NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
358,Wingate University,NC,199962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
359,Wisconsin Lutheran College,WI,240338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360,Xavier University of Louisiana,LA,160904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 361 entries, 0 to 360
Data columns (total 41 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   College Name  361 non-null    object
 1   State         361 non-null    object
 2   IPEDS ID      361 non-null    int64
 3   2023          200 non-null    object
 4   2022          222 non-null    object
 5   2021          221 non-null    object
 6   2020          215 non-null    object
 7   2019          229 non-null    object
 8   2018          172 non-null    object
 9   2017          178 non-null    object
 10  2016          176 non-null    float64
 11  2015          181 non-null    float64
 12  2014          182 non-null    object
 13  2013          180 non-null    object
 14  2012          182 non-null    object
 15  2011          188 non-null    float64
 16  2010          126 non-null    float64
 17  2009          124 non-null    float64
 18  2008          248 non-null    object
 19  2007          213 non-null    object
 20  2006          215 non-null    object
 21  2005          215 non-null    object
 22  2004          214 non-null    object
 23  2003          215 non-null    object
 24  2002          51 non-null     float64
 25  2001          159 non-null    object
 26  2000          158 non-null    object
 27  1999          159 non-null    object
 28  1998          159 non-null    object
 29  1997          161 non-null    object
 30  1996          162 non-null    object
 31  1995          161 non-null    object
 32  1994          141 non-null    object
 33  1993          141 non-null    object
 34  1992          141 non-null    object
 35  1991          142 non-null    object
 36  1990          25 non-null     float64
 37  1989          25 non-null     float64
 38  1988          26 non-null     float64
 39  1986          14 non-null     float64
 40  1984          12 non-null     float64
dtypes: float64(11), int64(1), object(29)
memory usage: 115.8+ KB

In [19]:
df.isnull()

,College Name,State,IPEDS ID,2023,2022,2021,2020,2019,2018,2017,...,1995,1994,1993,1992,1991,1990,1989,1988,1986,1984
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,False,False,False,True,True,True,True,False,True,True,...,True,True,True,True,True,True,True,True,True,True
357,False,False,False,True,False,False,False,True,True,True,...,True,True,True,True,True,True,True,True,True,True
358,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
359,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
360,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

,College Name,State,IPEDS ID,2023,2022,2021,2020,2019,2018,2017,...,1995,1994,1993,1992,1991,1990,1989,1988,1986,1984
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,False,False,False,True,True,True,True,False,True,True,...,True,True,True,True,True,True,True,True,True,True
357,False,False,False,True,False,False,False,True,True,True,...,True,True,True,True,True,True,True,True,True,True
358,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
359,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
360,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [20]:
df.loc[df.isnull().any(axis=1)]

,College Name,State,IPEDS ID,2023,2022,2021,2020,2019,2018,2017,...,1995,1994,1993,1992,1991,1990,1989,1988,1986,1984
5,Bowdoin College,ME,161004,6,6,6,6,5,3,6,...,6,6,6,4,4,13.0,9.0,12.0,10.0,NaN
7,United States Naval Academy,MD,164155,6,6,6,17,22,21,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Claremont McKenna College,CA,112260,9,8,6,7,9,8,9,...,12,11,16,14,13,21.0,18.0,23.0,NaN,NaN
9,United States Military Academy,NY,197036,9,11,15,21,18,12,19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Middlebury College,VT,230959,11,9,9,7,5,6,4,...,11,8,8,9,8,12.0,14.0,17.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,William Peace University,NC,199272,NaN,NaN,NaN,NaN,T2 (173-229),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
357,Williams Baptist University,AR,107877,NaN,T2 (168-222),T2 (171-221),T2 (164-215),NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
358,Wingate University,NC,199962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
359,Wisconsin Lutheran College,WI,240338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360,Xavier University of Louisiana,LA,160904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df.corr()

<ipython-input-22-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

,IPEDS ID,2016,2015,2011,2010,2009,2002,1990,1989,1988,1986,1984
IPEDS ID,1.000000,0.065700,0.046088,0.084075,0.095762,0.055665,0.228636,-0.039120,0.090557,0.023126,-0.352050,0.046385
2016,0.065700,1.000000,0.990136,0.947642,0.945973,0.939782,0.925360,0.522872,0.575054,0.304576,0.632689,0.433265
2015,0.046088,0.990136,1.000000,0.959750,0.941297,0.939045,0.919697,0.459238,0.516817,0.341202,0.680544,0.454152
2011,0.084075,0.947642,0.959750,1.000000,0.971979,0.970787,0.945061,0.540212,0.632201,0.313875,0.657923,0.489865
2010,0.095762,0.945973,0.941297,0.971979,1.000000,0.989589,0.952807,0.603770,0.655360,0.366105,0.669548,0.499222
2009,0.055665,0.939782,0.939045,0.970787,0.989589,1.000000,0.957397,0.637049,0.717561,0.378397,0.686317,0.506733
2002,0.228636,0.925360,0.919697,0.945061,0.952807,0.957397,1.000000,0.739900,0.771337,0.626643,0.659450,0.402464
1990,-0.039120,0.522872,0.459238,0.540212,0.603770,0.637049,0.739900,1.000000,0.909518,0.844177,0.654050,0.502548
1989,0.090557,0.575054,0.516817,0.632201,0.655360,0.717561,0.771337,0.909518,1.000000,0.840712,0.679247,0.609572
1988,0.023126,0.304576,0.341202,0.313875,0.366105,0.378397,0.626643,0.844177,0.840712,1.000000,0.907676,0.817915
1986,-0.352050,0.632689,0.680544,0.657923,0.669548,0.686317,0.659450,0.654050,0.679247,0.907676,1.000000,0.791791
1984,0.046385,0.433265,0.454152,0.489865,0.499222,0.506733,0.402464,0.502548,0.609572,0.817915,0.791791,1.000000

In [31]:
df['IPEDS ID'].sum()

67951963

In [41]:
df.mean()

<ipython-input-41-c61f0c8f89b5>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()

IPEDS ID    188232.584488
2016            86.829545
2015            89.342541
2011            92.824468
2010            61.896825
2009            61.169355
2002            25.215686
1990            12.880000
1989            13.000000
1988            13.307692
1986             7.071429
1984             5.916667
dtype: float64

In [44]:
df['1984'].median()

6.5

In [45]:
df['1984'].std()

3.058767824804721

In [56]:
df[df['1990']>=20]

,College Name,State,IPEDS ID,2023,2022,2021,2020,2019,2018,2017,...,1995,1994,1993,1992,1991,1990,1989,1988,1986,1984
8,Claremont McKenna College,CA,112260,9,8,6,7,9,8,9,...,12,11,16,14,13,21.0,18.0,23.0,NaN,NaN
16,Hamilton College,NY,191515,15,13,9,14,16,18,12,...,T1 (26-40),22,21,25,19,23.0,24.0,25.0,NaN,NaN
17,Barnard College,NY,189097,18,17,22,25,25,26,27,...,T1 (26-40),Q1 (26-35),Q1 (26-35),19,25,25.0,19.0,NaN,NaN,NaN
23,Colby College,ME,161086,24,17,15,11,18,12,12,...,23,17,15,20,18,23.0,22.0,NaN,NaN,NaN
24,Bates College,ME,160977,25,25,22,21,22,23,27,...,21,18,23,Q1 (26-35),19,21.0,21.0,NaN,NaN,NaN
43,Trinity College,CT,130590,39,46,44,46,46,44,38,...,22,24,24,Q1 (26-35),Q1 (26-36),20.0,NaN,NaN,NaN,NaN